---
- name: gslb wip audit and secondary member enable
  hosts: dev_f5
  connection: local
  gather_facts: true

  vars:
    wideip_responses: []
    combined_pools: []
    selected_wip: auction  # default, can be overridden via -e or survey

  tasks:
  - name: Get credentials from environment
    set_fact:
      ansible_user: "{{ lookup('env', 'ANSIBLE_NET_USERNAME') }}"
      ansible_password: "{{ lookup('env', 'ANSIBLE_NET_PASSWORD') }}"
    failed_when:
      - ansible_user is not defined or ansible_user == ''
      - ansible_password is not defined or ansible_password == ''
    no_log: true
    tags: audit

  - name: Validate selected_wip exists in wip_configs
    assert:
      that: "'{{ selected_wip }}' in wip_configs"
      fail_msg: "Invalid selected_wip '{{ selected_wip }}'. Available options: {{ wip_configs.keys() | list }}"
    tags: audit

  - name: Set selected WIP configuration
    set_fact:
      gslb_wip: "{{ wip_configs[selected_wip].gslb_wip }}"
      match_word: "{{ wip_configs[selected_wip].match_word }}"
    tags: audit

  - name: Debug selected WIP config
    debug:
      msg:
        - "Selected WIP: {{ selected_wip }}"
        - "gslb_wip: {{ gslb_wip }}"
        - "match_word: {{ match_word }}" 
    tags: audit

  - name: Authenticate to BIG-IP GTM
    include_role:
      name: f5_rest_login
    tags: audit

  - name: Include WideIP fetch task
    include_role: 
      name: fetch_wideip
    loop: "{{ gslb_wip }}"
    loop_control:
      label: "{{ item }}"
    vars:
      gslb_wip_item: "{{ item }}"
    tags: audit

  - name: Extract pool names from WideIP responses
    set_fact:
      pool_list: >-
        {{
          wideip_responses
          | map(attribute='json')
          | selectattr('name', 'in', gslb_wip)
          | map(attribute='pools')
          | map('first')
          | map(attribute='name')
          | list
          | unique
        }}
    tags: audit
     
  - name: Include pool members fetch task
    include_role:
      name: fetch_pool_members
    loop: "{{ pool_list }}"
    loop_control:
      label: "{{ item }}"
    vars:
      pool_name: "{{ item }}"
    tags: audit

  - name: Include pool stats fetch task
    include_role:
      name: fetch_pool_stats
    loop: "{{ pool_list }}"
    loop_control:
      label: "{{ item }}"
    vars:
      pool_name: "{{ item }}"
    tags: audit

  - name: Build combined_pools without block or custom filters
    set_fact:
      combined_pools: "{{ combined_pools + [combined_entry] }}"
    vars:
      pool_index: "{{ item }}"
      wip_name: "{{ gslb_wip[pool_index] }}"
      pool_name: "{{ pool_list[pool_index] }}"
      members: "{{ pool_members_responses[pool_index]['json']['items'] }}"
      stats: "{{ pool_stats_responses[pool_index].json.entries }}"
      enriched_members: >-
        {%- set enriched = [] -%}
        {%- for member in members -%}
          {%- set subpath = member.subPath -%}
          {%- set device_name = subpath.split(':')[0] if ':' in subpath else subpath -%}
          {%- set stat_path = 'https://localhost/mgmt/tm/gtm/pool/a/~Common~' ~ pool_name ~ '/members/~Common~' ~ member.name ~ ':~Common~' ~ device_name ~ '/stats' -%}
          {%- set stat = stats.get(stat_path, {}).get('nestedStats', {}).get('entries', {}) -%}
          {%- set enriched = enriched + [ {
            'name': member.name,
            'device_name': device_name,
            'availability': stat.get('status.availabilityState', {}).get('description', 'unknown'),
            'enabled': stat.get('status.enabledState', {}).get('description', 'unknown')
          } ] -%}
        {%- endfor -%}
        {{ enriched }}
      combined_entry:
        wip: "{{ wip_name }}"
        pool: "{{ pool_name }}"
        members: "{{ enriched_members }}"
    loop: "{{ range(0, pool_list | length) | list }}"
    loop_control:
      loop_var: item
    tags: audit

  - name: Show combined_pools for verification
    debug:
      var: combined_pools
    tags: audit

  - name: Determine disabled secondary members for enabling
    set_fact:
      availability_check: "{{ availability_check | default([]) + [ new_entry ] }}"
    vars:
      new_entry: >-
        {{
          pool_item
          | combine({
              'secondary_member': (
                pool_item.members
                | selectattr('name', 'defined')
                | selectattr('name', 'search', '(?i).*' + match_word + '.*')
                | selectattr('enabled', 'in', ['disabled', 'false', false])
                | list
              )[0] | default({})
            })
        }}
    loop: "{{ combined_pools }}"
    loop_control:
      loop_var: pool_item
      label: "{{ pool_item.pool }}"
    tags: audit

  - name: Log GTM pools with disabled secondary members for enabling
    debug:
      msg: |
        Pool: {{ item.pool }}
        WIP: {{ item.wip }}
        Secondary Member Found: {{ item.secondary_member.name if item.secondary_member.name is defined else 'None' }}
        Currently Enabled State: {{ item.secondary_member.enabled if item.secondary_member.enabled is defined else 'unknown' }}
        Eligible for Enable: {{ 'YES' if item.secondary_member.name is defined else 'NO' }}
    loop: "{{ availability_check }}"
    loop_control:
      label: "{{ item.pool }}"
    tags: audit

  - name: Include enable member task
    include_role: 
      name: enable_member
    loop: "{{ availability_check }}"
    loop_control:
      label: "{{ item.pool }}"
    tags: change

  - name: Include post-enable verification task
    include_role: 
      name: post_enable_check
    tags: change

  - name: Debug post_check_response
    debug:
      var: post_check_response.results
    tags: change

  - name: Assert secondary member is enabled after patch
    assert:
      that:
        - (item.json.enabled | default(false)) == true
      fail_msg: "Secondary pool member {{ item.json.name }} in pool {{ item.json.poolName | default('unknown') }} is NOT enabled!"
      success_msg: "Confirmed secondary pool member {{ item.json.name }} is successfully enabled."
    loop: "{{ post_check_response.results }}"
    loop_control:
      label: "Validate enable: {{ item.json.name  | default('unknown') }}"
    when: 
     - post_check_response is defined
     - "'json' in item"
    tags: change
