---
- name: Dynamic GSLB WIP Audit and Action
  hosts: dev_f5
  connection: local
  gather_facts: false

  vars_files:
    - wip_configs.yml

  vars:
    selected_wip: auction  # default, can be overridden via -e or survey

  tasks:

    - name: Validate selected_wip exists in wip_configs
      assert:
        that: "'{{ selected_wip }}' in wip_configs"
        fail_msg: "Invalid selected_wip '{{ selected_wip }}'. Available options: {{ wip_configs.keys() | list }}"

    - name: Set selected WIP configuration
      set_fact:
        gslb_wip: "{{ wip_configs[selected_wip].gslb_wip }}"
        match_word: "{{ wip_configs[selected_wip].match_word }}"

    - name: Debug selected WIP config
      debug:
        msg:
          - "Selected WIP: {{ selected_wip }}"
          - "gslb_wip: {{ gslb_wip }}"
          - "match_word: {{ match_word }}"

    - name: Your existing tasks continue here
      debug:
        msg: "Running tasks for {{ gslb_wip }} with match_word {{ match_word }}"

    # Your existing include_role or main logic below
