---
#  
# Expects variables: availability_check, ansible_host, partition, bigip_auth_token, retry_count, retry_delay

- name: Post-enable verification of secondary member with retries
  uri:
    url: >-
      https://{{ ansible_host }}/mgmt/tm/gtm/pool/a/~{{ partition }}~{{ item.pool }}/members/~{{ partition }}~{{ item.secondary_member.device_name }}:~{{ partition }}~{{ item.secondary_member.name }}
    method: GET
    headers:
      X-F5-Auth-Token: "{{ bigip_auth_token }}"
      Content-Type: application/json
    validate_certs: false
  register: post_check_response
  until: post_check_response.status in [200, 201]
  retries: "{{ retry_count }}"
  delay: "{{ retry_delay }}"
  failed_when: post_check_response.status not in [200, 201]
  when:
    - item.secondary_member is defined
    - item.secondary_member != {}
  loop: "{{ availability_check }}"
  loop_control:
    label: "Post-check for {{ item.pool }}"
